### ISSUE TITLE
Onchain reference design revision progress tracker

### ISSUE THREAD

**Issue by GBKS** [BitcoinDesign/Guide#1019]
This is a tracker issue for a larger chunk of work going on around revising the onchain reference designs in the guide (savings, shared, upgradeable). We discussed this thoroughly in jam sessions and our [working doc](https://docs.google.com/document/d/19n3-IaEuW1akrB1KcuHPJO3ZwKb0HJ5c1xdjVlRBWF0/edit?usp=sharing), so I'm moving this to an issue here for better tracking.

I'll group things by the likely page structure we'll have in the end. For all the details, see the [planning document](https://docs.google.com/document/d/19n3-IaEuW1akrB1KcuHPJO3ZwKb0HJ5c1xdjVlRBWF0/edit?usp=sharing).

**Reference designs**
- [ ] Savings wallet
- [ ] Shared wallet
- [ ] Upgradeable wallet
  - [ ] #777
- [ ] Wallet management
  - [ ] #867
  - [ ] #986

**How it works**
- [ ] Complex spending conditions
  - [ ] #992 
  - [ ] #847 
- [ ] Key rotation (via FROST)
- [ ] Musig (may be enough as a glossary entry)

I'll update this issue as we go.
