### ISSUE TITLE
Create page for Receiving bitcoin

### ISSUE THREAD

**Issue by johnsBeharry** [BitcoinDesign/Guide#174]
```meta
title: Receiving bitcoin
permalink: /guide/payments/receive
```

##### CONTENT STRUCTURE
This page should cover what to do when receiving bitcoin, how to share and copy addresses etc.

- Properties of a payment request
  - Address
  - Amount
  - Observer (who knows about the coin)
  - Memo (purpose of the payment)
- Types of addresses
  - Which addresses to support (native segwit by default)
- How to present QR codes (allow for specifying an amount)
- Single use / one-time addresses
  - Always generate a new address
  - Storing the payment request and showing the payment status
- Notifications and payment request status

##### TASKS
- [x] Write content draft
- [ ] Draft review
- [ ] Design header image
- [ ] Design content graphics and illustrations
- [ ] Layout content in Figma
- [ ] Develop layout and open PR
- [ ] Proof-reading (does it make sense)
- [ ] Technical review
- [ ] Internal review
- [ ] Proof-reading (grammar, typos)
- [ ] Cross-linking
- [ ] Proof-reading (grammar, typos)
- [ ] Consolidate
- [ ] Test on mobile
- [ ] Compress images
- [ ] Clean up source files and make them available
