### ISSUE TITLE
Create page for Transaction privacy

### ISSUE THREAD

**Issue by johnsBeharry** [BitcoinDesign/Guide#175]
This page should inform about what information is made public when sending or receiving, how the application can help minimise unnecessary privacy leaks, basic application functionality to help, and when we can, more advanced options.

- Public transactions
- Bitcoin's pseudonymous nature, and UTXO clusters
- Chain analysis
- Methods/protocols to enhance on-chain privacy
- Other user privacy considerations

---

##### TASKS
- [x] Write content draft
- [ ] Draft review
- [x] Design header image
- [ ] Design content graphics and illustrations
- [ ] Layout content in Figma
- [ ] Develop layout and open PR
- [ ] Proof-reading (does it make sense)
- [ ] Technical review
- [ ] Internal review
- [ ] Proof-reading (grammar, typos)
- [ ] Cross-linking
- [ ] Proof-reading (grammar, typos)
- [ ] Consolidate
- [ ] Test on mobile
- [ ] Compress images
- [ ] Clean up source files and make them available
