### ISSUE TITLE
Coin Selection Page To-Do 

### ISSUE THREAD

**Issue by pavlenex** [BitcoinDesign/Guide#360]
This issue is for keeping track of improvements needed on the newly added coin selection page in #90 

- [x] Better quality header image
![Screenshot 2021-05-28 at 18 12 38](https://user-images.githubusercontent.com/36959754/120013228-c85c3e00-bfe0-11eb-81a8-a1aa65d91da4.png)

- [x] Optimized first image for larger devices
![Screenshot 2021-05-28 at 18 12 44](https://user-images.githubusercontent.com/36959754/120013253-ce521f00-bfe0-11eb-8b5d-1f5c4589ae57.png)

- [x] Review all images
- [x] Add social preview image
- [x] Cut down on pros/cons and make them slightly more concise

**Comment by barefoot-88** [comment]
Hey @pavlenex , did you manage to fix these issues? Looks like you did but just wanted to check

**Comment by pavlenex** [comment]
Hey @barefoot-88 I still haven't, there are probably a few more items on to-do we're yet to discover. Feel free to tackle any of these or just add up to an already listed to-do above.

**Comment by GBKS** [comment]
Just took a quick look and looks like there's a lot of image-related stuff that needs fixing (folder location, image sizes, alt texts, height attributes). The usual.

**Comment by pavlenex** [comment]
@GBKS Any concrete steps we can suggest to @barefoot-88 for fixing these visuals so we can proceed with the issue?

**Comment by GBKS** [comment]
I ticked off 3 of the to-dos with #414. The to-do for optimizing that one image for wider screens would require re-exporting the image in a larger resolution (e.g. 1200px width) and updating the width and height on the picture include accordingly. @barefoot-88, is that something you could do?

Anyone willing to take on the last to-do about making pros and cons more concise?

**Comment by pavlenex** [comment]
@GBKS 
@barefoot-88 and I are on this. Ed will work on that image improvements, and I'll tackle the pros/cons sections.
