### ISSUE TITLE
Create page for Managing Funds

### ISSUE THREAD

**Issue by johnsBeharry** [BitcoinDesign/Guide#382]
```meta
title: Managing Funds
permalink: /guide/payments/management
```

Topics to cover:
- What is special about the bitcoin transaction history?
- State the primary attributes that need to be shown
- Saving meta data (Labeling)
- Define the available actions that are possible taking into consideration the different transaction states
- Transaction list vs coin list

Relates to #104

##### TASKS
- [ ] Write content draft
- [ ] Draft review
- [ ] Design header image
- [ ] Design content graphics and illustrations
- [ ] Layout content in Figma
- [ ] Develop layout and open PR
- [ ] Proof-reading (does it make sense)
- [ ] Technical review
- [ ] Internal review
- [ ] Proof-reading (grammar, typos)
- [ ] Cross-linking
- [ ] Proof-reading (grammar, typos)
- [ ] Consolidate
- [ ] Test on mobile
- [ ] Compress images
- [ ] Clean up source files and make them available

**Comment by pavlenex** [comment]
Does this mean we can close #104?

**Comment by GBKS** [comment]
To me, "Managing funds" sound like it should include things like spending analysis (groceries, utilities...) and multiple accounts (spending & savings, on-chain & Lightning). You think this would fit here, too?

**Comment by Bosch-0** [comment]
Just putting my suggestion here I made about some re-structuring which relates to this issue: https://bitcoindesign.slack.com/archives/C015856BDME/p1633071044084800 

The idea is we would have a chapter focusing on Mobile first, non-custodial, Bitcoin Lightning wallet design structured like:

`Designing a Bitcoin Wallet`
    - `On-boarding`
    - `Payments`
    - `Management` (this section would cover managing funds among other things).

**Comment by Bosch-0** [comment]
Closing this in favor of https://github.com/BitcoinDesign/Guide/issues/582 which covers the same content.
