### ISSUE TITLE
⚡️ Add Lightning to the guide - Progress overview 

### ISSUE THREAD

**Issue by danielnordh** [BitcoinDesign/Guide#478]
An issue to track overall progress of adding Lightning content to the guide.

**Chapters and pages to do / done**

- [x] Getting started
  - [x] Why Bitcoin is unique #477 
  - [x] Visual language #475 
  - [x] Technology primer #502
  - [x] Software overview #473 
  - [x] Hardware overview #476  
- [x] Designing Bitcoin products
  - [x] Why design for Bitcoin #488 
  - [x] Open design #588
  - [x] Principles #494 
  - [x] User research #485 
    - [x] User research resources #486 
  - [x] Usage life cycle #491 
  - [x] Personal finance #512 
  - [x] Common user flows #501 
  - [x] Wallet interoperability #503  
  - [x] Design resources #490 
- [x] Onboarding #520
  - [x] Getting to know your users #523
  - [x] Creating a new wallet #531
  - [x] Backing up a recovery phrase #541
    - [x] Automatic cloud backup #541
    - [x] Manual backup #541
  - [x] Restoring a wallet #524
  - [x] Protecting a wallet #537
  - [x] Funding a wallet #590
- [x] Private key management #542 
  - [x] Overview #563 
  - [x] Automatic cloud backup #559
  - [x] Manual backup #559 
  - [x] External signing device #555 
  - [x] Multi-key #564 
  - [x] Bitcoin backups #565 
- [x] Payments
  - [x] Transactions #593 
  - [x] Sending bitcoin #589
  - [x] Coin selection #586 
  - [x] Receiving bitcoin #574
  - [x] Transaction privacy #575
  - [x] Units & symbols
- [x] Case studies
  - [x] Daily spending #615
  - [x] Savings account #616
  - [x] Upgradeable account #617
  - [x] Shared account #618
- [x] Glossary  #479

**Comment by pavlenex** [comment]
Thanks for doing this, I'll pin this issue.

**Comment by GBKS** [comment]
Just updated the main comment with the "Designing Bitcoin products" section issues in Milestone 8.

**Comment by GBKS** [comment]
I think we can close this issue with our V2 wrap-up. It served it's purpose well.
