### ISSUE TITLE
Wallet Improvements Project - Issue Tracker

### ISSUE THREAD

**Issue by pavlenex** [BitcoinDesign/Guide#493]
This issue will serve as a ticket tracker of all the issues we, as Bitcoin Design Community identify on our design review calls and beyond. The goal is to allow us central place to keep track of all improvements proposals and their implementation.

Maintainers feel free to edit this comment to add new issues to the list, and anyone else feel free to post a links to the issues you've identified.

The screens of wallets we're reviewing can be found in this [Google Sheet.](https://docs.google.com/spreadsheets/d/1EI2qvVhb2XqfN4Ms2oDN8zl9-ReZ0acw2fG4Gmj6OBY/edit?usp=sharing)

## Blixt Wallet 
- [ ] https://github.com/hsjoberg/blixt-wallet/issues/377
- [x] https://github.com/hsjoberg/blixt-wallet/issues/378
- [ ] https://github.com/hsjoberg/blixt-wallet/issues/379
- [x] https://github.com/hsjoberg/blixt-wallet/issues/380
- [ ] https://github.com/hsjoberg/blixt-wallet/issues/381
- [x] https://github.com/hsjoberg/blixt-wallet/issues/382
- [ ] https://github.com/hsjoberg/blixt-wallet/issues/383
- [ ] https://github.com/hsjoberg/blixt-wallet/issues/384
- [x] https://github.com/hsjoberg/blixt-wallet/issues/386

## Bluewallet 
- [ ] https://github.com/BlueWallet/BlueWallet/issues/3885
- [ ] https://github.com/BlueWallet/BlueWallet/issues/4353
- [ ] https://github.com/BlueWallet/BlueWallet/issues/4463
- [ ] BlueWallet/LndHub#368
## Breez Wallet 
- [x] https://github.com/breez/breezmobile/issues/595
- [x] https://github.com/breez/breezmobile/issues/597
- [x] https://github.com/breez/breezmobile/issues/598
- [x] https://github.com/breez/breezmobile/issues/599
- [x] https://github.com/breez/breezmobile/issues/600

## Phoenix Wallet
- [ ] https://github.com/ACINQ/phoenix/issues/184
- [ ] https://github.com/ACINQ/phoenix/issues/196
- [ ] https://github.com/ACINQ/phoenix/issues/197
- [x] https://github.com/ACINQ/phoenix/issues/198
- [x] https://github.com/ACINQ/phoenix/issues/199
- [ ] https://github.com/ACINQ/phoenix/issues/200
- [x] https://github.com/ACINQ/phoenix/issues/204
- [ ] https://github.com/ACINQ/phoenix/issues/205
- [ ] https://github.com/ACINQ/phoenix/issues/208
- [ ] https://github.com/ACINQ/phoenix/issues/248 

## Bitcoin Design Guide improvements

Bellow are improvements that we've added to the Bitcoin Design Guide based on the reviews we've performed.

- [x] https://github.com/BitcoinDesign/Guide/issues/535
- [x] https://github.com/BitcoinDesign/Guide/issues/536

**Comment by moneyball** [comment]
We might want to wait until the LDK version is released before providing UI
feedback.

**Comment by GBKS** [comment]
Agreed. I mainly wanted to put together some examples for this initiative and hope that others join in. Roughly, I think we can discuss 4 levels of feedback:

1. Use case & audience (what user problems are being solved, who are the users, product-market fit...)
2. Spec (what features and tech is supported, are they appropriate for the use case...)
3. Interaction (is it easy to understand, navigate, use...)
4. Execution (layout, icons, colors...)

My examples were intentionally focused on the 4th type, as it's really easy to capture, discuss, and fix. Hopefully we get a few people to do these, I am curious what everyone thinks can be improved.

**Comment by Bosch-0** [comment]
Who's keen for another, I recommend [Zap](https://www.zaphq.io/). They're remote node only on mobile but the desktop has a neutrino light client mode. Feedback is also relevant to [Zeus redesign](https://github.com/BitcoinDesign/Meta/projects/4)

**Comment by pavlenex** [comment]
@Bosch-0 Let's set up one this Thursday. I must admit I've been slacking for the past few weeks on this one.

**Comment by Bosch-0** [comment]
Lock it :)

**Comment by GBKS** [comment]
@pavlenex just went through the unchecked links in the issue, all of them are still open.

The issue has gone a bit stale, but I think we can keep using it for any future issues we file with projects via the wallet design improvement project.

There are two additional issues I created with BlueWallet that were not part of the wallet improvement project. Should I add these here, too?
- https://github.com/BlueWallet/BlueWallet/issues/4353
- https://github.com/BlueWallet/BlueWallet/issues/4463

**Comment by Bosch-0** [comment]
Created issues where they did not exist for the zero amount invoice issue [Steve brought up](https://github.com/BitcoinDesign/Guide/issues/641) 

https://github.com/ACINQ/phoenix/issues/248 

https://github.com/BlueWallet/BlueWallet/issues/4497
